@server = http://localhost:8000

### test server 
GET {{server}}

### GET all content
GET {{server}}/contents

### GET byId contents
GET {{server}}/contents/2

### GET all users
GET {{server}}/users

### GET byId users
GET {{server}}/users/1

###POST users
POST {{server}}/users
Content-Type: application/json

{
    "username": "r",
    "password": 2468
}

###Put user
Put {{server}}/users/1
Content-Type: application/json

{
    "username": "jojlmgl",
    "password": 2468
}

###Delete userbyId
DELETE {{server}}/users/8
